<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="Tools\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Task1.QuestionnaireSub.Contract\Task1.QuestionnaireSub.Contract.csproj" />
  </ItemGroup>

</Project>
